// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  CallReducerFlags,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  DbContext,
  ErrorContextInterface,
  Event,
  EventContextInterface,
  Identity,
  ProductType,
  ProductTypeElement,
  ReducerEventContextInterface,
  SubscriptionBuilderImpl,
  SubscriptionEventContextInterface,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
} from "@clockworklabs/spacetimedb-sdk";
import { GameStatus as __GameStatus } from "./game_status_type";

export type GameState = {
  singletonId: number,
  score1: number,
  score2: number,
  status: __GameStatus,
  lastUpdate: Timestamp,
};

/**
 * A namespace for generated helper functions.
 */
export namespace GameState {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("singletonId", AlgebraicType.createU32Type()),
      new ProductTypeElement("score1", AlgebraicType.createU32Type()),
      new ProductTypeElement("score2", AlgebraicType.createU32Type()),
      new ProductTypeElement("status", __GameStatus.getTypeScriptAlgebraicType()),
      new ProductTypeElement("lastUpdate", AlgebraicType.createTimestampType()),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: GameState): void {
    GameState.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): GameState {
    return GameState.getTypeScriptAlgebraicType().deserialize(reader);
  }

}


